### PR TITLE
implement ButterKnife library for ArtsFragment module

### PR DESCRIPTION
**Pull request by snufflesrea**
implement ButterKnife library for ArtsFragment module
#6

### CODE REVIEW

**Comment by snufflesrea** [comment]
Btw the changed suppose only on Arts-fragment file. But every time I squash commits, the number of FIles changed always increasing. Do you have any idea, why it is happen?

**Comment by r4dixx** [comment]
Awesome @snufflesrea! Thank you. I'll have a look asap (currently busy with finishing Udacity's remaining course). But as soon as I have a minute I'll look into it. About your question:

- Files in `.idea` are IDE dependent (actually I shouldn't have included these in the repo). I'll add them to `.gitignore`. You can ignore them. 
  - For some reason, I don't really know why, `.idea/gradle.xml` always change the project directory from `$PROJECT_DIR$` to my actual project directory and vice-versa... another good reason to add this to `.gitignore` I guess :smile: 
  - `.idea/caches/build_file_checksums.ser` is pretty self-explanatory. I need to add that to `.gitignore` too
- Now about `app/build.gradle` and `app/src/main/java/com/r4dixx/visitcalgary/MainActivity.java`, it seems you simply didn't update the project from the latest version in `master` before implementing new changes (i.e. this commit), so they're marked as new and it's an expected behavior. That's no big deal, next time simply make sure you `git pull` the latest version before starting to work on a new pull request. What you did here is starting to work from where you left i.e. before I merged your first pull request and made other changes.

Hope that makes things clearer for you! Thank you again for your contribution :+1:

**Comment by r4dixx** [comment]
Actually, my bad. You need to do more than a `git pull`, which seems pretty obvious now that I think of it. Sorry, I'm pretty new to GitHub :smile: But I found this and I think it might be useful for you: https://help.github.com/articles/syncing-a-fork/

**Review by r4dixx — CHANGES_REQUESTED** [review]
Make sure to sync your fork before committing new changes. This PR should only contain changes for the ArtsFragment.java file. See this PR conversation and the GitHub documentation for more: https://help.github.com/articles/syncing-a-fork/

More importantly, any reason why you didn't use @BindDrawable for R.drawable resources in ArtsFragment? (Asking genuinely as I'm new to this)

**Comment by snufflesrea** [comment]
Adding the changes on drawable now

**Review by r4dixx — APPROVED** [review]
Thanks! However compilation fails because @BindDrawable expects a Drawable type. The Place class expects an int (an image resource ID) and PlaceAdapter as well. Here's the output: 

error: @BindDrawable field type must be 'Drawable'. (com.r4dixx.visitcalgary.ArtsFragment.balletDraw)

I'm approving this pull request because in the scope of ArtsFragment it works, but Place and PlaceAdapter must be updated consequently. I'll have a look.

**Pull request merged**
